In [39]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

pd.set_option("display.max_columns", None)

In [40]:
data_path = Path("/Users/tsantaloic/Desktop/Projet_05_AIA02/data/raw")

dfs = []

for file in data_path.glob("*.csv"):
    df = pd.read_csv(file)
    df["category"] = file.stem  # sécurité si jamais
    dfs.append(df)

df_all = pd.concat(dfs, ignore_index=True)

df_all.shape

(21000, 11)

df.duplicated().sum()

In [41]:
# Suppression des doublons
df_all.duplicated().sum()

np.int64(10)

In [42]:
df_all[df_all.duplicated(keep=False)]

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,category
4735,5.0,gift,I got this shirt as a gift and he loved it! H...,[],B0051HUKQQ,B073VZGPST,AE5UW4XLVL5AXSJP24MTH4LKK4DA,1367582332000,1,True,Automotive
4736,5.0,gift,I got this shirt as a gift and he loved it! H...,[],B0051HUKQQ,B073VZGPST,AE5UW4XLVL5AXSJP24MTH4LKK4DA,1367582332000,1,True,Automotive
13273,5.0,Piano Solo,I am singing solo for Christmas Cantata...this...,[],B0012A4SFA,B0012A4SFA,AEQ4BRZQAEE7UKKOPVTM2EQVGV3A,1384398192000,1,True,Digital_Music
13274,5.0,Piano Solo,I am singing solo for Christmas Cantata...this...,[],B0012A4SFA,B0012A4SFA,AEQ4BRZQAEE7UKKOPVTM2EQVGV3A,1384398192000,1,True,Digital_Music
13340,5.0,great price,great product. great price,[],B002LVGU82,B002LVGU82,AHKQKE46BOZQDE6TIKGSOUS3NEYQ,1548159682656,0,True,Digital_Music
13341,5.0,great price,great product. great price,[],B002LVGU82,B002LVGU82,AHKQKE46BOZQDE6TIKGSOUS3NEYQ,1548159682656,0,True,Digital_Music
13427,5.0,Scurve E. Dogs...,"Scuttle me bones, me buckoes, 'ere be more sal...",[],B00A82J4X4,B00A82J4X4,AEK27DQ54G7PIWW627UHT72TFX4A,1359670654000,1,False,Digital_Music
13428,5.0,"Every time I hear that song, I cry...","Our Song... as another reviewer rightly said, ...",[],B000024SYI,B000024SYI,AEK27DQ54G7PIWW627UHT72TFX4A,1109754319000,16,True,Digital_Music
13429,5.0,Scurve E. Dogs...,"Scuttle me bones, me buckoes, 'ere be more sal...",[],B00A82J4X4,B00A82J4X4,AEK27DQ54G7PIWW627UHT72TFX4A,1359670654000,1,False,Digital_Music
13430,5.0,"Every time I hear that song, I cry...","Our Song... as another reviewer rightly said, ...",[],B000024SYI,B000024SYI,AEK27DQ54G7PIWW627UHT72TFX4A,1109754319000,16,True,Digital_Music
14817,5.0,Definitive Document,"Maybe Marvin Game's best work, worth seeking o...",[],B00C9QLT8U,B00C9QLT8U,AFLPIQCVZCBUJF3BZGYH75VWV2SA,1484046388000,0,False,Digital_Music
14818,4.0,Excellent recording of a San Francisco favorite,Excellent recording of a San Francisco favorit...,[],B003Q3S3UW,B003Q3S3UW,AFLPIQCVZCBUJF3BZGYH75VWV2SA,1417297011000,1,False,Digital_Music
14819,4.0,Long coveted bootleg now available.,A great snapshot of a unique sounding band. Al...,[],B00CD8SZCM,B00CD8SZCM,AFLPIQCVZCBUJF3BZGYH75VWV2SA,1391463883000,1,True,Digital_Music
14820,5.0,Definitive Document,"Maybe Marvin Game's best work, worth seeking o...",[],B00C9QLT8U,B00C9QLT8U,AFLPIQCVZCBUJF3BZGYH75VWV2SA,1484046388000,0,False,Digital_Music
14821,4.0,Excellent recording of a San Francisco favorite,Excellent recording of a San Francisco favorit...,[],B003Q3S3UW,B003Q3S3UW,AFLPIQCVZCBUJF3BZGYH75VWV2SA,1417297011000,1,False,Digital_Music
14822,4.0,Long coveted bootleg now available.,A great snapshot of a unique sounding band. Al...,[],B00CD8SZCM,B00CD8SZCM,AFLPIQCVZCBUJF3BZGYH75VWV2SA,1391463883000,1,True,Digital_Music
14838,5.0,Relaxing and joyful,This two-disc collection of instrumental Chris...,[],B014VATBG8,B014VATBG8,AGX26GKPUFEHTDBTE7PDC45FOM2A,1678509433753,0,True,Digital_Music
14839,5.0,Relaxing and joyful,This two-disc collection of instrumental Chris...,[],B014VATBG8,B014VATBG8,AGX26GKPUFEHTDBTE7PDC45FOM2A,1678509433753,0,True,Digital_Music
14868,5.0,Good packaging for great albums.,I like how they made them like mini LP's inclu...,[],B09YHYWRF6,B09YHYWRF6,AGQRRV3PURFW32M33CFUGR4RZDNQ,1661552518787,0,True,Digital_Music
14869,5.0,Good packaging for great albums.,I like how they made them like mini LP's inclu...,[],B09YHYWRF6,B09YHYWRF6,AGQRRV3PURFW32M33CFUGR4RZDNQ,1661552518787,0,True,Digital_Music

In [43]:
df_all[df_all.duplicated()]

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,category
4736,5.0,gift,I got this shirt as a gift and he loved it! H...,[],B0051HUKQQ,B073VZGPST,AE5UW4XLVL5AXSJP24MTH4LKK4DA,1367582332000,1,True,Automotive
13274,5.0,Piano Solo,I am singing solo for Christmas Cantata...this...,[],B0012A4SFA,B0012A4SFA,AEQ4BRZQAEE7UKKOPVTM2EQVGV3A,1384398192000,1,True,Digital_Music
13341,5.0,great price,great product. great price,[],B002LVGU82,B002LVGU82,AHKQKE46BOZQDE6TIKGSOUS3NEYQ,1548159682656,0,True,Digital_Music
13429,5.0,Scurve E. Dogs...,"Scuttle me bones, me buckoes, 'ere be more sal...",[],B00A82J4X4,B00A82J4X4,AEK27DQ54G7PIWW627UHT72TFX4A,1359670654000,1,False,Digital_Music
13430,5.0,"Every time I hear that song, I cry...","Our Song... as another reviewer rightly said, ...",[],B000024SYI,B000024SYI,AEK27DQ54G7PIWW627UHT72TFX4A,1109754319000,16,True,Digital_Music
14820,5.0,Definitive Document,"Maybe Marvin Game's best work, worth seeking o...",[],B00C9QLT8U,B00C9QLT8U,AFLPIQCVZCBUJF3BZGYH75VWV2SA,1484046388000,0,False,Digital_Music
14821,4.0,Excellent recording of a San Francisco favorite,Excellent recording of a San Francisco favorit...,[],B003Q3S3UW,B003Q3S3UW,AFLPIQCVZCBUJF3BZGYH75VWV2SA,1417297011000,1,False,Digital_Music
14822,4.0,Long coveted bootleg now available.,A great snapshot of a unique sounding band. Al...,[],B00CD8SZCM,B00CD8SZCM,AFLPIQCVZCBUJF3BZGYH75VWV2SA,1391463883000,1,True,Digital_Music
14839,5.0,Relaxing and joyful,This two-disc collection of instrumental Chris...,[],B014VATBG8,B014VATBG8,AGX26GKPUFEHTDBTE7PDC45FOM2A,1678509433753,0,True,Digital_Music
14869,5.0,Good packaging for great albums.,I like how they made them like mini LP's inclu...,[],B09YHYWRF6,B09YHYWRF6,AGQRRV3PURFW32M33CFUGR4RZDNQ,1661552518787,0,True,Digital_Music

In [44]:
df_all = df_all.drop_duplicates()

In [45]:
df_all.duplicated().sum()

np.int64(0)

In [46]:
# Harmonisation des types 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   rating             3000 non-null   float64
 1   title              3000 non-null   object
 2   text               3000 non-null   object
 3   images             3000 non-null   object
 4   asin               3000 non-null   object
 5   parent_asin        3000 non-null   object
 6   user_id            3000 non-null   object
 7   timestamp          3000 non-null   int64
 8   helpful_vote       3000 non-null   int64
 9   verified_purchase  3000 non-null   bool
 10  category           3000 non-null   object
dtypes: bool(1), float64(1), int64(2), object(7)
memory usage: 237.4+ KB

In [47]:
# Conversion du timestamp
df["timestamp"] = pd.to_datetime(df["timestamp"], unit="ms")

In [48]:
#Encodage des IDs (pour le ML)
df["user_id_enc"] = df["user_id"].astype("category").cat.codes
df["item_id_enc"] = df["parent_asin"].astype("category").cat.codes

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   rating             3000 non-null   float64
 1   title              3000 non-null   object
 2   text               3000 non-null   object
 3   images             3000 non-null   object
 4   asin               3000 non-null   object
 5   parent_asin        3000 non-null   object
 6   user_id            3000 non-null   object
 7   timestamp          3000 non-null   datetime64[ns]
 8   helpful_vote       3000 non-null   int64
 9   verified_purchase  3000 non-null   bool
 10  category           3000 non-null   object
 11  user_id_enc        3000 non-null   int16
 12  item_id_enc        3000 non-null   int16
dtypes: bool(1), datetime64[ns](1), float64(1), int16(2), int64(1), object(7)
memory usage: 249.2+ KB

In [50]:
df_all.shape

(20990, 11)

In [51]:
df.isna().sum().sort_values(ascending=False)

rating               0
title                0
text                 0
images               0
asin                 0
parent_asin          0
user_id              0
timestamp            0
helpful_vote         0
verified_purchase    0
category             0
user_id_enc          0
item_id_enc          0
dtype: int64

In [52]:
df["rating"] = df["rating"].fillna(df["rating"].mean())

In [53]:
df = df.dropna(subset=["user_id", "parent_asin"])

In [54]:
# Standardisation robuste avec gestion std=0
mean = df["rating"].mean()
std = df["rating"].std()
if std == 0 or pd.isna(std):
    # si pas de variance, mettre 0 partout (ou NaN selon votre choix)
    df["rating_norm"] = 0.0
else:
    df["rating_norm"] = (df["rating"] - mean) / std

In [55]:
#
df_model = df[[
    "user_id_enc",
    "item_id_enc",
    "rating_norm",
    "timestamp"
]].copy()

df_model.head()

   user_id_enc  item_id_enc  rating_norm               timestamp
0          307         1878    -0.126107 2021-01-30 22:07:31.196
1          307          968     0.629025 2018-08-16 18:18:37.349
2          467         2463     0.629025 2021-08-17 21:21:44.798
3          467         1569    -0.126107 2020-05-26 05:14:42.910
4          467          129     0.629025 2014-08-25 19:23:08.000

In [56]:
from pathlib import Path

# Dossier "processed" à côté du notebook (adapte si nécessaire)
processed_dir = Path("/Users/tsantaloic/Desktop/Projet_05_AIA02/data/processed")
processed_dir.mkdir(parents=True, exist_ok=True)  # crée le dossier s'il n'existe pas

# Sauvegarde en CSV sans l'index
output_path = processed_dir / "df_model.csv"
df_model.to_csv(output_path, index=False)

print(f"CSV enregistré: {output_path}")

CSV enregistré: /Users/tsantaloic/Desktop/Projet_05_AIA02/data/processed/df_model.csv

In [57]:
from pathlib import Path

processed_dir = Path("/Users/tsantaloic/Desktop/Projet_05_AIA02/data/processed")
processed_dir.mkdir(parents=True, exist_ok=True)

cleaned_path = processed_dir / "amazon_reviews_cleaned.csv"

df.to_csv(cleaned_path, index=False)

cleaned_path

PosixPath('/Users/tsantaloic/Desktop/Projet_05_AIA02/data/processed/amazon_reviews_cleaned.csv')

In [58]:
df_model = df[[
    "user_id_enc",
    "item_id_enc",
    "rating_norm",
    "timestamp"
]].copy()

model_path = processed_dir / "amazon_reviews_model.csv"
df_model.to_csv(model_path, index=False)

model_path

PosixPath('/Users/tsantaloic/Desktop/Projet_05_AIA02/data/processed/amazon_reviews_model.csv')

In [62]:
train_path = processed_dir / "train.csv"
test_path = processed_dir / "test.csv"

train.to_csv(train_path, index=False)
test.to_csv(test_path, index=False)

train_path, test_path

(PosixPath('/Users/tsantaloic/Desktop/Projet_05_AIA02/data/processed/train.csv'),
 PosixPath('/Users/tsantaloic/Desktop/Projet_05_AIA02/data/processed/test.csv'))

In [63]:
import pandas as pd

pd.read_csv(model_path).head()
pd.read_csv(train_path).shape, pd.read_csv(test_path).shape

((69, 4), (18, 4))